steps:
- name: "ubuntu"
  args: ["echo", "hello world"]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    "run",
    "--user", "root",
    "-v", "/workspace:/src",
    "iodide/pyodide-env:0.16.1",
    "make"]
  env:
    - "EMSDK_NUM_CORES=8"
    - "EMCC_CORES=8"
timeout: 1800s
options:
  machineType: N1_HIGHCPU_8