steps:
- name: "ubuntu"
  args: ["echo", "hello world"]
- name: "gcr.io/cloud-builders/docker"
  args: [
    "run",
    "--user", "root",
    "-v", "/workspace:/workspace",
    "gcr.io/program-world-dev/gpk-pyodide:asyncify-v20200717a",
    "/rsync_and_make.sh"]
  env:
    - "EMSDK_NUM_CORES=8"
    - "EMCC_CORES=8"
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  args: ["gsutil", "-h", "Cache-Control:no-cache,max-age=0", "cp", "/workspace/build/*", "gs://dev.gpkpw.com/gpk-pyodide/$BRANCH_NAME/"]
timeout: 7200s
options:
  machineType: N1_HIGHCPU_8